### ISSUE TITLE
SockettingListener/IdentifyingListener DEBUG spam.

### ISSUE THREAD

**Issue by mibby** [PixelOutlaw/MythicDrops#346]
MythicDrops v4.1.3 snapshot from https://artifactory.pixeloutlaw.io/artifactory/public/com/tealcube/minecraft/bukkit/mythicdrops/4.1.3-SNAPSHOT/
Paper dev 1329 (Spigot 1.12.2)

MythicDrops seems to have created a new folder in the main server directory called pixeloutlaw with a file named mythicedrops.log. Inside that file is a bunch of debug lines such as;

```
06:05:02.855 DEBUG c.t.m.b.m.s.SockettingListener - onRightClick() - event.getAction() != RIGHT_CLICK_AIR && event.getAction() != RIGHT_CLICK_BLOCK
```

This is despite debug being set false in the plugin config.

**Comment by mibby** [comment]
Also, shouldn't the debug file be inside the main plugin directory, not creating a new directory in the root server folder? It would make more sense to contain everything within plugins/MythicDrops/.

**Comment by Nunnery** [comment]
The design of that is intentional. The debug config option is a legacy option and does not function.

pixeloutlaw folder creation is also intentional and cannot be put inside the plugins folder, as it's possible for server owners to configure the location of the plugins folder to be somewhere else. Bukkit does not expose an API for me to know where the location of that folder is.

**Comment by Nunnery** [comment]
Will add ability to toggle the debug using the legacy option.

**Comment by mibby** [comment]
> as it's possible for server owners to configure the location of the plugins folder to be somewhere else

Not as far as I know. Besides, why not write the debug file to the root of the MythicDrops folder, reading and writing the same way configs are loaded normally?

**Comment by Nunnery** [comment]
MythicDrops folder location isn't available at the time the logging is currently configured, which is before Bukkit initialization.

https://bukkit.gamepedia.com/CraftBukkit_Command_Line_Arguments

You could use the --plugins argument to change the plugins directory for CraftBukkit, not sure if that still remains for Spigot.

**Comment by mibby** [comment]
I doubt many people point their plugins folder to a new area. In any case, don't hardcode plugin location when writing the debug file. Just use the main directory for the plugin itself and initialize the debugger once the plugin has loaded, not before bukkit initialization.

**Comment by Nunnery** [comment]
I didn't write the debugger, I'm using logback in order to make logging easier, which creates the output file at the time a Logger is created, and if the Logger is created as a static variable ([which it is, as it's a best practice](https://github.com/Nunnery/MythicDrops/blob/master/src/main/java/com/tealcube/minecraft/bukkit/mythicdrops/MythicDropsPlugin.java#L102)), it will happen the first time the class is referenced. The MythicDrops class first gets referenced by the Bukkit server before the MythicDrops directory in the plugin folder is populated for use, so I have no way of properly configuring it to use the MythicDrops plugin folder. The fix for that was to use the pixeloutlaw folder.
